### ISSUE TITLE
N-am văzut nimic aci despre GTFS - poate n-ar strica să vedeți ce mai fac și alții

### ISSUE THREAD

**Issue by florinj** [gov-ithub/infotranspub-web#14]
[https://en.wikipedia.org/wiki/General_Transit_Feed_Specification](https://en.wikipedia.org/wiki/General_Transit_Feed_Specification)
[https://googleblog.blogspot.ro/2005/12/public-transit-via-google.html](https://googleblog.blogspot.ro/2005/12/public-transit-via-google.html)
[https://github.com/google/transitfeed/wiki](https://github.com/google/transitfeed/wiki)
[https://github.com/google/transitfeed/wiki/FeedValidator](https://github.com/google/transitfeed/wiki/FeedValidator)
[https://transit.land/feed-registry/?offset=50](https://transit.land/feed-registry/?offset=50)
[http://wiki.openstreetmap.org/wiki/General_Transit_Feed_Specification](http://wiki.openstreetmap.org/wiki/General_Transit_Feed_Specification)
[https://transitfeeds.com/](https://transitfeeds.com/)
[https://maps.google.com/landing/transit/index.html](https://maps.google.com/landing/transit/index.html)
[https://trilliumtransit.zendesk.com/hc/en-us/articles/200919096-What-is-GTFS-](https://trilliumtransit.zendesk.com/hc/en-us/articles/200919096-What-is-GTFS-)
[http://www.transitchicago.com/developers/gtfs.aspx](http://www.transitchicago.com/developers/gtfs.aspx)

**Comment by kagix** [comment]
Am luat in considerare feedback-ul.

**Comment by kagix** [comment]
Acum exista  un set de pagini Confluence (Starea lumii) dedicat informatiilor despre GTFS
